security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }
        user_in_database:
            entity:
                class: App\Entity\User
                property: email
    
    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_USER
        ROLE_USER:
        ROLE_BANNED:
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_in_database
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_parameter: _csrf_token  
                csrf_token_id: authenticate 
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    # Restrictions d'accès (Access Control)
    # access_control:
    #     # Zone d'administration (ROLE_ADMIN requis)
    #     - { path: ^/admin, roles: ROLE_ADMIN }
    #     # Accès au profil utilisateur (ROLE_USER requis)
    #     - { path: ^/profile, roles: ROLE_USER }
    #     # Empêche les utilisateurs authentifiés de revenir à /login
    #     - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     # Accès à la racine pour tous les utilisateurs, connectés ou non
    #     - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon